protected/controllers/AdmSpecializController.php
<?php

class AdmSpecializController extends Controller {

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    public function accessRules() {
        return array(
            // array('deny',
            //     'actions'=>array('admin'),
            //     'users'=>array('?'),
            // ),
            array('allow',
                'actions' => array('Admin', 'DeleteSpecializ', 'EditSpecializ', 'AddSpecializ'),
                //'roles'=>array('sex'),
                //'users'=>array('vadimka108@gmail.com'),
                'expression' => 'Yii::app()->user->role=="sex"',
            ),
            array('deny',
                'actions' => array('Admin', 'DeleteSpecializ', 'EditSpecializ', 'AddSpecializ'),
                'users' => array('*'),
            ),
        );
    }

    public function actionAdmin() {

        $model = new Specializ('searchDao');
        if (isset($_GET['Specializ'])) {
            $model->attributes = $_GET['Specializ'];
            // CVarDumper::dump($model->attributes,100,true);
            // echo '=============';
            // CVarDumper::dump($_GET['Specializ'],100,true);
            // echo '=============';
        }
        if (Yii::app()->request->isAjaxRequest)
            $this->renderPartial('admin', array('SqldataProvider' => $model));
        else
            $this->render('admin', array('SqldataProvider' => $model));
    }

    public function actionDeleteSpecializ($id) {
        //$modelVerify = GkhZayavka::model()->findAll('id_specializ=:id_specializ',array(':id_specializ'=>$id));
        if (false) { //(count($modelVerify)>0)
            echo 'Невозможно удалить, есть связанные заявки';
        } else {
            CatSpecializ::model()->deleteAll('id_t_specializ=:id_t_specializ', array(':id_t_specializ' => $id));
            $model = Specializ::model()->findByPk($id);
            $model->delete();
        }

        //SpecializDates::delAll($model->id);
        //$model->delete();
    }

    public function actionEditSpecializ($id) {
        $model = Specializ::model()->with('specializDates')->findByPk($id);
        $this->performAjaxValidation($model);

        if (isset($_POST['Specializ'])) {
            //unset ($_POST['Specializ']['id_cat']);
            $model->attributes = $_POST['Specializ'];
            if ($model->save()) {
                if (isset($_POST['SpecializDates']))
                    SpecializDates::saveDates($_POST['SpecializDates'], $model->id);
                else
                    SpecializDates::delAll($model->id);

                if (isset($_POST['cat']))
                    CatSpecializ::saveSelection($_POST['cat'], $model->id);
                else
                    CatSpecializ::delAll($model->id);
                if (isset($_POST['Relation']))
                    Relation::saveRelationDirections($model->id, $_POST['Relation']['id_directions']);
                else
                    Relation::saveRelationDirections($model->id, array());
            }
            else
                $this->redirect(array("site/error"));
            $this->redirect(Yii::app()->createUrl('Specializ/view', array('id' => $model->id)));
        }
        $this->render('_formSpecializ', array('model' => $model));
    }

    public function actionAddSpecializ() {
        $model = new Specializ;
        $this->performAjaxValidation($model);

        if (isset($_POST['Specializ'])) {
            $model->attributes = $_POST['Specializ'];
            if ($model->save()) {
                if (isset($_POST['SpecializDates']))
                    SpecializDates::saveDates($_POST['SpecializDates'], $model->id);
                else
                    SpecializDates::delAll($model->id);

                if (isset($_POST['cat']))
                    CatSpecializ::saveSelection($_POST['cat'], $model->id);
                else
                    CatSpecializ::delAll($model->id);
            }
            else
                $this->redirect(array("site/error"));
            $this->redirect(Yii::app()->createUrl('Specializ/view', array('id' => $model->id)));
        }
        $this->render('_formSpecializ', array('model' => $model));
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'specializ-_formSpecializ-form') {
            echo CActiveForm::validate($model);
            //echo 'true';
            Yii::app()->end();
        }
    }

}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	public $layout='/layouts/column2';
	
     public function actionFile()
    {
        //номер функции обратного вызова
        $callback = $_GET['CKEditorFuncNum'];
          //имя фалйа
           $file_name = $_FILES['upload']['name'];
           //временное имя файла на сервере
           $file_name_tmp = $_FILES['upload']['tmp_name'];
           //указываем куда складывать изображения
           $file_new_name = 'file/';
           //формируем полный путь к изображению
           $full_path = $file_new_name.$file_name;
           //формируем адрес для атрибута src тега img
           $http_path = '/file/'.$file_name;
           $error = '';
           if( move_uploaded_file($file_name_tmp, $full_path) ) {} 
           else
           {
               $error = 'Some error occured please try again later';
               $http_path = '';
            }
            echo "<script type=\"text/javascript\">
                 window.parent.CKEDITOR.tools.callFunction(".$callback.",  \"".$http_path."\", \"".$error."\" );
             </script>";
    }
	
	public function actionLic()
	{
		$this->render('lic');
	}
	public function actionBrowse() {
		// я создал специально отдельный пустой лейаут
		$this->layout='//layouts/clear';
		$this->render('browser');
	}
	public function actionRegistration()
	{
	        // тут думаю все понятно
	        $form = new User();

	        // Проверяем являеться ли пользователь гостем
	        // ведь если он уже зарегистрирован - формы он не должен увидеть.
	        if (!Yii::app()->user->isGuest) {
	             throw new CException('Вы уже зарегистрированны!');
	        } else {
	            // Если $_POST['User'] не пустой массив - значит была отправлена форма
	            // следовательно нам надо заполнить $form этими данными
	             // и провести валидацию. Если валидация пройдет успешно - пользователь
	            // будет зарегистрирован, не успешно - покажем ошибку на экран
	            if (!empty($_POST['User'])) {
	                
	                 // Заполняем $form данными которые пришли с формы
	                $form->attributes = $_POST['User'];
	                
	                // Запоминаем данные которые пользователь ввёл в капче
	                 $form->verifyCode = $_POST['User']['verifyCode'];
	                
	                    // В validate мы передаем название сценария. Оно нам может понадобиться
	                    // когда будем заниматься созданием правил валидации [читайте дальше]
	                     if($form->validate('registration')) {
	                        // Если валидация прошла успешно...
	                        // Тогда проверяем свободен ли указанный логин..

	                            if ($form->model()->count("email = :email", array(':email' => $form->email))) {
	                                 // Указанный логин уже занят. Создаем ошибку и передаем в форму
	                                $form->addError('email', 'Email уже занят');
	                                $this->render("registration", array('form' => $form));
	                             } else {
	                             	$form->real = $form->password;
	                             	$form->password = md5($form->password);
	                                // Выводим страницу что "все окей"
	                                if ($form->save())
	                                	$this->render("registration_ok");
	                                else
	                                	$this->render('error', $error);
	                            }
	                                             
	                    } else {
	                        // Если введенные данные противоречат 
	                        // правилам валидации (указаны в rules) тогда
	                        // выводим форму и ошибки.
	                         // [Внимание!] Нам ненадо передавать ошибку в отображение,
	                        // Она автоматически после валидации цепляеться за 
	                        // $form и будет [автоматически] показана на странице с 
	                         // формой! Так что мы тут делаем простой рэндер.
	                        
	                        $this->render("registration", array('form' => $form));
	                    }
	             } else {
	                // Если $_POST['User'] пустой массив - значит форму некто не отправлял.
	                // Это значит что пользователь просто вошел на страницу регистрации
	                // и ему мы должны просто показать форму.
	                 
	                $this->render("registration", array('form' => $form));
	            }
	        }
	 }

    // public function init()
    // {
    //     parent::init();
    //     Yii::app()->urlManager->setAppLanguage();
    // } 
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
// Обработчик сообщений от файл-менеджера
            'fileManager'=>array(
                'class'=>'ext.yiiext.widgets.elfinder.ElFinderAction',
            ),
			
			'upload' => array('class' => 'xupload.actions.XUploadAction', 'path' => Yii::app() -> getBasePath() . "/../images/uploads", "publicPath" => Yii::app()->getBaseUrl()."/images/uploads" ),
			
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
				'foreColor'=>'#000000',
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	public function actionAbout()
	{
		//О нас
		$model = Page::model()->findByPk('1');
		$this->render('application.views.page.view', array('model'=>$model));
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		//О нас
		//$model = Page::model()->findByPk('1');
		//$this->render('application.views.page.view', array('model'=>$model));
		$direct = Direction::model()->findAll();
		$news=new CActiveDataProvider('News',array(
			'criteria'=>array(
        		'condition' => 'type=0'
        )));
		$this->render('application.views.direction.indexDirection', array('direct'=>$direct,'news'=>$news));		
	}

	public function actionUslugi()
	{
		//О нас
		//$model = Page::model()->findByPk('1');
		//$this->render('application.views.page.view', array('model'=>$model));
		$direct = Direction::model()->findAll();
		$this->render('uslugi', array('direct'=>$direct));		
	}

	public function actionOar()
	{
		//О нас
		//$model = Page::model()->findByPk('1');
		//$this->render('application.views.page.view', array('model'=>$model));
		$this->render('oar', array());		
	}
	public function actionOros()
	{
		//О нас
		//$model = Page::model()->findByPk('1');
		//$this->render('application.views.page.view', array('model'=>$model));
		$this->render('oros', array());		
	}
	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
	    		echo $error['message'];
	    	else
	        	$this->render('error', $error);
	    } else $this->render('error', $error);
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact($isAbout = true)
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$headers="From: {$model->email}\r\nReply-To: {$model->email}";
				mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact',Yii::t('site', 'Thank you for contacting'));
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model, 'isAbout'=>$isAbout,));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}

	public function actionTest()
	{
		$data=array();
		$treeList1=Jmenu::model()->findAll();
		foreach ($treeList1 as $i=>$model) {
		  $data[$i]=$this->formatData($model);
		  $treeList2=$model->children();
		  foreach ($treeList2 as $j=>$submodel) {
			$data[$i]['children'][]=$this->formatData($submodel);
		  };
		};		
		$this->render('__test', array('data'=>$data));
	}
  protected function formatData(&$tree)
  {
	  return array('url'=>'#');
    if($tree->children())
      return array('text'=>CHtml::link($tree->name,"#"),'id'=>$tree->id,'expanded'=>true);
    else
      return array('text'=>CHtml::link($tree->name,"#"),'id'=>$tree->id);
  }
 	
}

protected/views/admSpecializ/_formSpecializ.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'specializ-_formSpecializ-form',
	'enableAjaxValidation'=>false,
	'clientOptions' => array(
		'validateOnSubmit' => true,
		'validateOnChange' => false,
	),
)); ?>

	<p class="note">Поля помеченные <span class="required">*</span> обязательны.</p>

	<?php echo $form->errorSummary($model); ?>

<div class="row span-25">

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>110)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row span-13">
		<!-- <div class="row"> -->
			<?php 
				// echo $form->labelEx($model,'id_f_direction');
				// $data = CHtml::listData(Direction::model()->findAll(), 'id', 'name');
				// echo $form->dropDownList($model,'id_f_direction', $data);
				// echo $form->error($model,'id_f_direction');
			?>
		<!-- </div> -->

		<div class="row">
			<?php 
				echo $form->labelEx($model,'id_kurs');
				$dataKurs = CHtml::listData(Kurs::model()->findAll(), 'id', 'name');
				echo $form->dropDownList($model,'id_kurs', $dataKurs, array('prompt'=>'Выберите курс:') );
				echo $form->error($model,'id_kurs');
			?>
		</div>

		<div class="row span-10">
			<?php echo $form->labelEx($model,'id_org'); ?>
			<?php echo $form->dropDownList($model,'id_org', CHtml::listData(Org::model()->findAll(), 'id','name_small'),
						array('prompt'=>'Выберите юр.лицо:')  ); ?>
			<?php echo $form->error($model,'id_org'); ?>
			<div>Если не указанна организация, то будет показан(а) организация и адрес из направления этой специальности</div>
		</div>
	</div>

	<div class="row span-10">
		<div class="row">
			<?php echo $form->labelEx($model,'times'); ?>
			<?php echo $form->textField($model,'times'); ?>
			<?php echo $form->error($model,'times'); ?>
		</div>
            
		<div class="row">
                    
			<?php echo $form->labelEx($model,'cost_all'); ?>
			<?php echo $form->textField($model,'cost_all'); ?>
			<?php echo $form->error($model,'cost_all'); ?>
                    <div>Если общая стоимость> 0, то стоимость первичная и ежегодная будут скрыты.</div>
		</div>
            
		<div class="row">
			<?php echo $form->labelEx($model,'cost'); ?>
			<?php echo $form->textField($model,'cost'); ?>
			<?php echo $form->error($model,'cost'); ?>
		</div>

		<div class="row">
			<?php echo $form->labelEx($model,'cost_year'); ?>
			<?php echo $form->textField($model,'cost_year'); ?>
			<?php echo $form->error($model,'cost_year'); ?>
		</div>
    </div>


	<div class="clear"></div>	
        
	<?php
		if($model->name){
			$this->widget('ext.widgets.multiselects.XMultiSelects',array(
			    'leftTitle'=>'Включенные направления',
			    'leftName'=>'Relation[id_directions][]',
			    'leftList'=>  Direction::getAllDirectionIn($model->id),
			    'rightTitle'=>'Не включенные направления',
			    'rightName'=>'Specializ[id_directions][]',
			    //'rightList'=>  array_diff(Direction::getAllDirectionIn($model->id),  Direction::getAllDirections()),
                            'rightList'=>  array_diff(Direction::getAllDirections(),Direction::getAllDirectionIn($model->id)),
			    'size'=>20,
			    'width'=>'400px',
			));
		} 
	?>
        
</div>

	<?php 
	$this->widget('ext.yiiext.widgets.ckeditor.ECKEditor',array(
		'model'=>$model,                # Data-Model (form model)
		'attribute'=>'body',         # Attribute in the Data-Model
		//'editorTemplate'=>'full',	
		//'editorTemplate' => 'advanced',
		//"toolbar"=>"basic",
		'skin'=>'office2003',
		'options'=>array(
//			'editorTemplate'=>'basic',		
//                'toolbar' => array(
//                    array('Bold','Italic','Underline','Strike','-','NumberedList','BulletedList','-','Outdent','Indent','Blockquote','-','Link','Unlink','-','Table','SpecialChar','-','Cut','Copy','Paste','-','Undo','Redo','-','Maximize',),
//                ),
            'filebrowserBrowseUrl'=>CHtml::normalizeUrl(array('site/browse')),
			'filebrowserImageBrowseUrl'=>CHtml::normalizeUrl(array('site/browse')),
			//'filebrowserUploadUrl'=>CHtml::normalizeUrl(array('site/browse')),
			'filebrowserUploadUrl'=>CHtml::normalizeUrl(array('site/file')),

        ),
	) );
	?>

<div class='vids row span-12'>
<?php 
$AllSelection= CHtml::listData(CatSpecializ::model()->catSpec(), 'id', 'name_cat');
$Selected = CatSpecializ::catSel($model->id);

echo CHtml::checkBoxList('cat', $Selected, $AllSelection);
//echo //$form->error($model->catSpecializs, 'id_t_cat'); 
?>
</div>
<style>
.vids input{
	float: left;
}
</style>

<div class="row span-8 the_dates">
 
<label for="Specializ_dates">Даты</label> 
	<?php
		//echo $form->labelEx($model->specializDates,'date'); 
		foreach($model->specializDates as $i=>$item) {
			echo '<div class="clear"></div>';
			$item['date'] = date("d.m.Y",strtotime($item['date']));
			echo CHtml::activeTextField($item,"[$i]date");
			echo Chtml::button('удалить', array(
				'name'=>'del',
				'onclick'=>'delOpt('.$i.')',
				'id'=>'SpecializDatesD_'.$i.'_date',
				//'htmlOptions'=>array('class'=>'deletes'),
				));
			// $this->widget('zii.widgets.jui.CJuiDatePicker', array(
			//    'name' => $i.'_date',
			//    'model' => $item,
			//    'attribute' => '[$i]date',
			//    'language' => 'ru',
			//    'options' => array(
			//        'showAnim' => 'fold',
			//    ),
			//    'htmlOptions' => array(
			//        'style' => 'height:20px;'
			//    ),
			// )); 
			echo $form->error($item,"[$i]date");
			echo '<div class="clear"></div>';
		}
	?>
	

 
<input type="button" class="treeSmall" value=" + Добавить дату" onclick="addOpt()">

	<div class="clear"></div>

</div>

	<div class="clear"></div>
	<div class="row buttons">
		<?php echo CHtml::submitButton('Сохранить');  ?>
	</div>
<?php $this->endWidget(); ?>
 

</div><!-- form -->

<script>
function addOpt() 
{
	count = $(".the_dates input[type='text']").length;
	inputOpt = '<input name="SpecializDates[' + count + '][date]" id="SpecializDates_' + count + '_date" type="text"  value="26-07-2012">';
	inputDel = '<input name="del" onclick="delOpt(' + count + ')" id="SpecializDatesD_' + count + '_date" type="button" value="удалить">';
	$(".the_dates").append(inputOpt);
	$(".the_dates").append(inputDel);
}

function delOpt(i)
{
	$('#SpecializDates_' + i + '_date').remove();
	$('#SpecializDatesD_' + i + '_date').remove();
}
</script>

protected/views/admSpecializ/admin.php
<?php
$this->pageTitle=Yii::app()->name . ' - '. 'Прайс лист';//$direct->name;
$this->breadcrumbs=array(
	'',
	//'Направления'=>array('/Direction/index'),
	//$direct->name,
);
?>

<?php
if (Yii::app()->user->isAdmin)
	echo '<h2> Администрирование специальностей </h2>';
else
	echo '<h1> Прайс лист </h1>';
?>


<div id="detail"></div>
<?php


if (Yii::app()->user->isAdmin)
	echo CHtml::Button("Создать специальность", array(
		'submit'=>Yii::app()->createUrl('AdmSpecializ/AddSpecializ'),
	));

?>


<div>
	 
	<br/><a href="/file/price2013.xlsx">Прайс лист (скачать) .</a>
	<br/> 
</div>
<br/> 

<div class="row span-10">
<?php
echo CHtml::dropDownList(
		'Specializ[dir_name]', 
		'', 
		CHtml::listData(Direction::model()->findAll(), 'id', 'name'),
		array(
			'prompt'=>'Выбор направления (ВСЕ)',
			'onchange'=>"$.fn.yiiGridView.update('specializ', {data: $(this).serialize()});")
		);
?>
</div>

	
<?php
$this->widget('ext.groupgridview.GroupGridView', array(
	'id'=>'specializ',
	//'dataProvider'=>$SqldataProvider,//$SqldataProvider->searchDao(), 
	'dataProvider'=>$SqldataProvider->searchDao(),
	'filter'=>$SqldataProvider,
	'mergeColumns' => array('dir_name','spec_name'),  
	//'cssFile' => false,
	'pager' => array(
		//'cssFile' => false,
	),
	'columns'=>array(
	// array(
			// 'header'=>'Направление',
			// 'name'=>'dir_name',
			// 'value'=>'$data["dir_name"]',
			// 'filter'=>CHtml::listData(Direction::model()->findAll(), 'id', 'name'),
		// ),
		array(
			'header'=>'Специальность',
			'name'=>'spec_name',
			'type'=>'raw',
			'value'=>'CHtml::link($data["spec_name"],Yii::app()->createUrl("/Specializ/view/", array("id"=>$data["id"])))',
		),

		array(
			'header'=>'Категория',
			'name'=>'name_cat',
			'filter'=>CHtml::listData(Cat::model()->findAll(), 'id', 'name_cat'),
		),
		array(
			'header'=>'Стоимость',
			'name'=>'cost',
			//'value'=>'$data["cost"]',
			'filter'=>false,
		),
		array(
			'header'=>'Ст.годовая',
			'name'=>'cost_year',
			//'value'=>'$data["cost"]',
			'filter'=>false,
		),			
		array(
			'header'=>'Курс',
			'name'=>'kurs',
			'filter'=>CHtml::listData(Kurs::model()->findAll(), 'id', 'name'),
			'value'=>'$data["kursname"]',
		),
		array(
			'visible'=>Yii::app()->user->isAdmin,
			'htmlOptions'=>array('style'=>'text-align: center'),
			'header'=>'Редактировать',
			'name'=>'spec_name',
			'filter'=>false,
			'type'=>'raw',
			'value'=>'Chtml::link("edit",Yii::app()->createUrl("AdmSpecializ/EditSpecializ/",
				array("id"=>$data["id"])))',
		),
		array(
			'visible'=>Yii::app()->user->isAdmin,
			'header'=>'delete',
			'name'=>'spec_name',
			'filter'=>false,
			'type'=>'raw',
			//'value'=>'CHtml::link("удалить","#")',
			 'value'=>'Chtml::link("delete",Yii::app()->createUrl("AdmSpecializ/deleteSpecializ/",
			 	array("id"=>$data["id"], "asDialog"=>1)))',
			'htmlOptions'=>array('style'=>'text-align: center',
				//'onclick'=> 'showDialog( $(this).attr( \'href\' ) ); return false;'),
			'onclick'=> 'showDialog( $(this).find("a").attr( \'href\' ) ); return false;'),
 
		),
		/*array(
			//'class'=>'CButtonColumn',
			//'template'=>'',//'{view}{update}{delete}',
			
			'buttons' => array(
				'view'=>array(
					'url'=>'Yii::app()->createUrl("rates/rates/ViewRate", array("id"=>$data["id"],"asDialog"=>1))',
				),
				'update'=>array(
					'url'=>'Yii::app()->createUrl("rates/rates/update", array("id"=>$data["id"]))',
				),
				/* - РАБОЧИЙ СКРИПТ НА УДАЛЕНИЕ v0.1
				'delete'=>
					array(
						'click'=>'function(){$("#cru-frame").attr("src",$(this).attr("href")); $("#cru-dialog").dialog("open");  return false;}',
						'url'=>'Yii::app()->createUrl("rates/rates/delete", array("id"=>$data["id"],"asDialog"=>1))',
						'options'=>array(  
						'ajax'=>array(
							'type'=>'POST',
							// ajax post will use 'url' specified above 
							'url'=>"js:$(this).attr('href')", 
							'update'=>'#viewRate',
							),
						),
				),*/
				/* - РАБОЧИЙ СКРИПТ НА УДАЛЕНИЕ v1.1 + с диалоговым окном*/
				/*
				'delete'=>array(
						'url'=>'Yii::app()->createUrl("rates/rates/delete", array("id"=>$data["id"],"asDialog"=>1))',
				), 
			),
			
		),*/
	),
)); 

$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
    'id'=>'mydialog',
    // additional javascript options for the dialog plugin
	'options'=>array(
		'title'=>'Modal Dialog',
		'width'=>400,
		'height'=>200,
		'autoOpen'=>false,
		'resizable'=>false,
		'modal'=>true,
		'overlay'=>array(
			'backgroundColor'=>'#000',
			'opacity'=>'0.5'
		),
		'buttons'=>array(
			'OK'=>'js:function(){isok();}',
			'Cancel'=>'js:function(){iscancel();}',    
		),
	),
));
echo 'Вы действительно хотите удалить ?';
$this->endWidget('zii.widgets.jui.CJuiDialog');
?>


<script type="text/javascript">
/**
 * url на удаление ставки (id_r_rates)
 */
var uri;

/**
 * Функция показывающая диалоговое окно
 * @param string - url на удаление ставки (id_r_rates)
 */
function showDialog(urlZ){
	uri = urlZ;
	$('#mydialog' ).dialog( { title: 'Подвердите действие' } ).dialog( 'open' ); 
}

/**
 * Диалоговое окно: пользователь нажал ок
 * 1. Посылаем запрос на удаление ставки
 * 2. Результат показываем в #viewRate
 * 3. Обновляем Грид
 */
function isok() {
	$("#detail").html('');
	$.ajax({ 
		'url': uri,
		'cache':false,
		'success':function(html){ 
			$('#mydialog').dialog('close');
			$("#detail").html(html);
			$.fn.yiiGridView.update("specializ"); // update (Название грида)
		} 
	});
}

/**
 * Пользователь нажал отмену, закрываем диалоговое окно
 */
function iscancel() {
	$('#mydialog').dialog('close');
}

</script> 