protected/controllers/PageController.php
<?php

class PageController extends Controller
{
	public $layout='/layouts/column2';

	public function actionView($id)
	{
        $this->getIsAccess($id);

		$model = Page::model()->with('jfiles')->findByPk($id);
        if (count($model) == 1)
            $this->render('view', array('model' => $model));
        else {
            $model = News::model()->findByPk($id);
            if (count($model) == 1)
                $this->render('redirect', array('model' => $model));
            throw new CHttpException(404, 'Указанная запись не найдена');
        }
	}

	public function actionNews()
	{
		$criteria = new CDbCriteria();
		$criteria->condition='type=1';
		$criteria->order='date_created DESC';
		$count=Page::model()->count($criteria);

		$pages=new CPagination($count);
		$pages->pageSize=50;
		$pages->applyLimit($criteria);

		$models=Page::model()->findAll($criteria);

		$this->render('indexNews',array(
			'models'=>$models,
			'pages'=>$pages,
		));
	}

    private function getIsAccess($id) {
        if ((Yii::app()->user->isGuest) && ($id=='70')) {
            Yii::app()->controller->redirect(array('user/login'));
        }
    }
}

protected/views/page/indexNews.php
<?php
$this->pageTitle=Yii::app()->name . ' - '. 'Новости';//$direct->name;
$this->breadcrumbs=array(
	'Новости',
	//'Направления'=>array('/Direction/index'),
	//$direct->name,
);
?>

<?php
foreach ($models as $model) {
	echo Yii::app()->dateFormatter->format('d MMMM yyyy', $model->date_created);
	echo '<h4>';
	echo CHtml::link($model->title, Yii::app()->createUrl('/page/view',array('id'=>$model->id)));
	echo '</h4>';
}
?>
<?php 
$this->widget('CLinkPager', array(
	'pages' => $pages,
));
?>

protected/views/page/redirect.php
<?php
header("HTTP/1.1 301 Moved Permanently");
header("Location: http://specialist-gkh.ru/news/$model->id");
exit();
?>

protected/views/page/view.php
<?php
//$this->pageTitle=Yii::app()->name . ' - '. 'О нас';//$direct->name;
$this->pageTitle='Обучение специалистов ЖКХ. ' . ' - '. $model->title .'. Курсы ЖКХ Москва.';
$this->breadcrumbs= 
	$model->linkNews;
	//'Направления'=>array('/Direction/index'),
	//$direct->name,
 
?>

<div class="row">
<h3><?=$model->title?></h3>
</div>


<?php
if (count($model->jfiles )>0) {
	echo '<div class="right">';
	echo '<strong>Приложения</strong>';
	foreach ($model->jfiles as $key => $value) {
		echo '<div>';
		switch ($value['name']) {
			case '': $fName = 'файл'; break; 
			default: $fName = $value['name']; break;
		} 
		echo CHtml::link($fName, sprintf($value['file'],''));
		echo '</div>';
	}
	echo '</div>';
}
?>

 
<?php
$this->menu=array(
    array('label'=>'Редактировать', 'url'=>array('AdmPage/EditPage', 'id'=>$model->id)),
    array('label'=>'Все страницы', 'url'=>array('AdmPage/admin')),
);
?>
 
<div class="clearfixs"></div>
<?php //echo imgResizeHtml::getImgFromHtml($model->body); ?>

<div><?=$model->body?></div>

<?php 
//CVarDumper::dump($model->Gallary,100,1);
if (!is_null($model->Gallary)) {
    
    $this->renderPartial('application.modules.gallary.views.gallary._preview5',array('model'=>$model->Gallary));
}
?>